### PR TITLE
Add `disableThirdPartySharing` method on Adjust SDK

### PR DESCRIPTION
**Pull request by tp**

### CODE REVIEW

**Comment by tp** [comment]
Would've liked to update the SDK to 4.21.0 already, but that seems to come with some breaking changes, so I stayed with the minimal amount of changes here.

**Comment by uerceg** [comment]
Wow @tp, pretty impressive, thanks for this! 👏

What breaking changes did you notice with 4.21.0?

**Comment by tp** [comment]
> What breaking changes did you notice with 4.21.0?

Just 3 compile errors. Probably nothing major, but I needed to apply the migration steps outlined here: https://github.com/adjust/ios_sdk/blob/master/doc/migrate.md

**Comment by uerceg** [comment]
:+1: No need to worry about that, we can take it from here and do few minor things for alignment with 4.21.0, this what you did is already majority of work done. Thank you one more time, we'll try to push this update as soon as we can.

**Comment by uerceg** [comment]
Replaced with https://github.com/adjust/flutter_sdk/pull/16.

**Pull request closed without merging**
