### PR TITLE
Migrated to null safety

### PR DESCRIPTION
**Pull request by blaueeiner**

### CODE REVIEW

**Comment by uerceg** [comment]
Hey @blaueeiner 

Thanks for the PR! We will take a look and try to build our next Flutter SDK update based around it.

**Comment by uerceg** [comment]
@blaueeiner One follow up question in here. With these changes, seems like breaking changes are being introduced in the SDK which will make it not usable for anyone who is using SDK version lower than 2.12.0, right? If yes, is there a way in which code which supports null safety can still be compiled for those who are compiling their apps with SDK version prior to 2.12.0?

**Comment by firatcetiner** [comment]
@uerceg 

> @blaueeiner One follow up question in here. With these changes, seems like breaking changes are being introduced in the SDK which will make it not usable for anyone who is using SDK version lower than 2.12.0, right? If yes, is there a way in which code which supports null safety can still be compiled for those who are compiling their apps with SDK version prior to 2.12.0?

The null-safety feature is backward compatible with old Dart SDK releases. Using `Dart SDK >= 2.12` in this plugin doesn't necessarily mean that clients who use this plugin should also upgrade to Dart SDK `version` `>= 2.12` on their app. So there won't be any issues related to Dart SDK versioning in the environment.

**Comment by uerceg** [comment]
@firatcetiner Thanks!

**Comment by blaueeiner** [comment]
@uerceg Why is this still not merged yet?

**Comment by firatcetiner** [comment]
@blaueeiner What do you think about [this](https://github.com/blaueeiner/flutter_sdk/pull/1)? It is a breaking change but I think it was necessary.

**Comment by IchordeDionysos** [comment]
@blaueeiner @firatcetiner I do like the PR and the new API 🤔 

Makes unit-testing a lot easier and would be great preparation to at some point migrate the Adjust SDK to a federated package.

**Comment by blaueeiner** [comment]
@firatcetiner Great changes. Since I am not an official, I cannot tell you more than it is a great change because of the reasons @IchordeDionysos mentioned. I hope both PRs will be merged soon.

**Comment by firatcetiner** [comment]
> It cannot be real that nearly the whole ecosystem of packages already updated to null safety and Adjust, a service you are paying for, did not do any changes on their own yet.

Totally agreed. I expected that at least the methods would be asynchronous as my PR suggest. But I think you could merge my [PR](https://github.com/blaueeiner/flutter_sdk/pull/1) with your fork and then Adjust team can decide what to do with your PR, right? @blaueeiner

**Comment by blaueeiner** [comment]
@firatcetiner Sure I will consider that 👍

**Comment by augustorsouza** [comment]
Let´s merge this PR, guys?

**Comment by uerceg** [comment]
Hey guys, sorry not sure which time now for delay, we had some priorities shifting on our end. We're back on this topic next week and we expect to have this done in a week or two afterwards.

**Comment by uerceg** [comment]
🥁 Replaced with https://github.com/adjust/flutter_sdk/pull/52. @blaueeiner thank you one more time for contribution and to all the rest - sorry for delays and thanks for your patience.

**Pull request closed without merging**
